include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/**.freezed.dart
    - lib/**/**.g.dart
  errors:
    # Remi さんの推奨設定
    # https://github.com/dart-lang/sdk/issues/46844
    # freezed モデルの invalid_annotation_target の警告を消す目的
    invalid_annotation_target: ignore

linter:
  rules:
    - require_trailing_commas
